### ISSUE TITLE
Broken symlinks in core after migration when the move option is used

### ISSUE THREAD

**Issue by mkrizek** [ansible-community/collection_migration#109]
```
ERROR: Found 2 symlinks issue(s) which need to be resolved:
ERROR: lib/ansible/modules/notification/_osx_say.py:0:0: broken symlinks are not allowed
ERROR: lib/ansible/modules/system/_python_requirements_facts.py:0:0: broken symlinks are not allowed
```

e.g. `lib/ansible/modules/notification/_osx_say.py` -> `lib/ansible/modules/notification/say.py`, the symlink is not moved, the target file is.

**Comment by bcoca** [comment]
this is currently 'expected' .. unsure how to go forward since we have contradictory mandates at this point: migrate all out, but collections won't support deprecation nor aliases

**Comment by bcoca** [comment]
closing as dupe of #187, those are consequence of same deprecation/aliases issue
