### ISSUE TITLE
rewrite  powershell for collections

### ISSUE THREAD

**Issue by bcoca** [ansible-community/collection_migration#11]
Current migration only addresses python plugins, powershell is mostly just copied but imports are not rewritten to function within the collection.
from
```
#Requires -Module Ansible.ModuleUtils.NameOfModuleUtil 
```
to
```
#AnsibleRequires AnsibleCollections.namespace.collection.NameOfModuleUtil
```
 and  from
```
lib/ansible/module_utils/powershell/Ansible.ModuleUtils.NameOfModuleUtil.psm1 
```
to
```
plugins/module_utils/NameOfModuleUtil.psm1 
```

**Comment by bcoca** [comment]
cc @nitzmahone @jborean93  we might need to consult with you for this item

**Comment by nitzmahone** [comment]
This could get a little gnarly and span languages, depending on what we collection-ize... If we start moving/renaming C# module utils as well, there's potentially some nasty chains of PS->PS->C# (and other permutations). Off the top of my head, we'd need to find/replace:
* PS module_utils "imports" (eg `#Requires -Module`, `#AnsibleRequires -Module` and `#AnsibleRequires -CSharpUtil`)
* C# namespace declarations (eg `namespace Foo.Bar { }`)
* C# namespace imports (eg `using Foo.Bar`)

* PS usages of C#-declared types (eg `[Foo.Bar]::Thing)

OTOH, I don't think that's necessary for 2.10- most of the PS and C# module_utils are good "base functionality" that's not specific to any particular modules, so unless/until we try to go "totally bare" or completely externalize Windows support, those things should just stay where they are (which means the modules that use them don't need to change).

**Comment by webknjaz** [comment]
@bcoca let's wait then, maybe?

**Comment by bcoca** [comment]
@nitzmahone @webknjaz 'totally bare' Ansible is one of the requested scenarios, I know it has lost push lately, but until it is totally off the table it is something we still need to deal with.

**Comment by jborean93** [comment]
So while we are planning on keeping all existing module utils for PowerShell and C# in Ansible utils that have been added in 2.10 (currently only `csharp/Ansible.Service.cs` will be moved to a collection.

So technically we could still implement this functionality or we could just move the files manually and change the import (in the 1 module) that uses it.

**Comment by bcoca** [comment]
closing as per above
