### ISSUE TITLE
Support tests in spec

### ISSUE THREAD

**Issue by mkrizek** [ansible-community/collection_migration#131]
In addition to test discovery, provide a means to specify tests (integration/unit) in spec. Note that `test` key is for `lib/ansible/plugins/test` currently.

**Comment by gundalow** [comment]
Note that this needs to include all plugin types and module_utils

Also `lib/ansible/module_utils/postgres.py` has a valid test called `test/units/module_utils/postgresql/test_postgres.py`

**Comment by bcoca** [comment]
right now we autodetect tests, that should work for all plugin types, not just modules.

**Comment by bcoca** [comment]
closed via #365
