### ISSUE TITLE
Integration tests don't need to use FQCN

### ISSUE THREAD

**Issue by gundalow** [ansible-community/collection_migration#156]
@mattclay has said that `ansible-test` has been updated to make the current Collection default, so no need to rewrite the `test/integration/target` files anymore.

This should hopefully speed up the migration process.

**Comment by mkrizek** [comment]
Plugins from other collections that the integration tests use probably still need to be rewritten.

**Comment by mattclay** [comment]
Modules in the current collection do not need to be rewritten. Plugins (lookups, filters, etc.) do need to be rewritten, as well as modules in other collections.
