### ISSUE TITLE
Error (or warn) if scenario tries to migrate previous migrated (migrated_to)

### ISSUE THREAD

**Issue by gundalow** [ansible-community/collection_migration#165]
Assuming that `migrate.py` might be run multiple times against ansible/ansible it would be good to ensure content doesn't get migrated multiple times.

For example, it seems likely that we might migrate Grafana content earlier than other content (though maybe not git rm from ansible/ansible). We wouldn't want a follow up migration.py run to try and put Grafana in another collection

1) The initial run of migrate.py would generate an updated `BOTMETA.md` which includes `migrated_to`
2) PR raised to update ansible/ansible:devel's `BOTMETA.md`  (can be done by hand)
3) The second run of `migrate.py` would error if it detects `migrated_to` for any content mentioned in the scenario files.

Once https://github.com/ansible/ansible/pull/64029 has been merged and

**Comment by webknjaz** [comment]
Well, we could auto-send PRs too, this would require installation of https://github.com/apps/ansible-collection-migrator into ansible/ansible.

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/pull/64029 has been merged

**Comment by bcoca** [comment]
@gundalow for 'already migrated content' rename the collection with leading `_` then it becomes 'advisory' and we don't touch that collection, only consider it for dependencies.

@webknjaz no, once something is migrated manually, we are not going to intervene with this process, just document the fact and use if for dependency handling.

**Comment by gundalow** [comment]
What about for content that's already been migrated into a Collection, eg F5, GCP though not deleted from ansible/ansible.

We don't necessarily have those scenario files, do we need to manually make a scenario file after the fact? 

Since BOTMETA.YML should already have this info, can't we use that?

**Comment by bcoca** [comment]
@gundalow i'm already documenting those, see the 'bcs' scenario, currently they still generate collections but that is just for comparison/testing, once we are happy with 'migrate.py' i'll rename to _ leading names to make them 'advisory only'. As for deleting or not, afaik that has not been decided yet AND those doing manual migration are responsible for their files, this migration is only dealing with that which was NOT manually migrated already.

**Comment by bcoca** [comment]
@gundalow  added grafana 'advisory' collection entry to my main scenario https://github.com/ansible-community/collection_migration/blob/master/scenarios/bcs/ansible_community.yml

**Comment by bcoca** [comment]
closing as per above
