### ISSUE TITLE
[TODO] Fix autopushing to GitHub

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/collection_migration#167]
Apparently, it's broken and I'm pretty sure that it's because we push CI workflow files. It's a known problem with HTTPS but SSH pushes should be fine.

So my suggested solution is to pre-create deploy keys in repos before push and then use them. After pushing we need to clean them up.

Refs:
* https://developer.github.com/v3/repos/keys/#add-a-new-deploy-key
* https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys

**Comment by mkrizek** [comment]
I disabled injecting CI workflow files (https://github.com/ansible-community/collection_migration/commit/7c60bb6e7a1e1c643aadc3a161bdd3c2dd45be48) but it still failed https://github.com/ansible-community/collection_migration/runs/339977395. Not sure if I missed something.

**Comment by mkrizek** [comment]
I tried using `--force` instead of `--force-with-lease`, ended up with:

```
! [remote rejected]   HEAD -> master (refusing to allow a bot to create or update workflow `.github/workflows/collection-continuous-integration.yml`)`
```

Disabled until this is fixed: https://github.com/ansible-community/collection_migration/commit/9531e68b767271b67e44b320afe51242d7dc881c

**Comment by pabelanger** [comment]
IMO, we should not be pushing directly to projects, but opening PRs for projects to review and merge. This also gives the option for tests to run against proposed code. This maybe means, dropping support directly in the migrate script for this, and writing CI jobs.

**Comment by pabelanger** [comment]
https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_3a/3a0f5562db3aab78062374b3d999e027366d4b67/post/propose-network-collections-migration-arista-eos/4bb2e86/job-output.html

for example, is how we solved this in ansible-network.

**Comment by bcoca** [comment]
@pabelanger we wont be migrating files for EXISTING projects, only for those that have not already migreated
