### ISSUE TITLE
ansible-minimal contains broken symlinks causing pip install to fail

### ISSUE THREAD

**Issue by gundalow** [ansible-community/collection_migration#177]
https://github.com/ansible-community/collection_migration/issues/172 gave us nightly builds, when I tested this in [Grafan CI](https://github.com/gundalow-collections/grafana/pull/15) I found

```
pip install git+https://github.com/ansible-collection-migration/ansible-minimal
...
2019-12-09T18:32:31.8949102Z     creating build/lib/ansible/modules/identity
2019-12-09T18:32:31.8949596Z     copying lib/ansible/modules/identity/__init__.py -> build/lib/ansible/modules/identity
2019-12-09T18:32:31.8950167Z     error: can't copy 'lib/ansible/modules/identity/_onepassword_facts.py': doesn't exist or not a regular file
```

This appears to be because as `_onepassword_facts.py` points to non-existent `onepassword_info.py`

This is a rename, rather than a deprecation.

Note there maybe other just broken symlinks.

Possibly related, we also have module directories with only `__init__.py` files  - https://github.com/ansible-collection-migration/ansible-minimal/tree/devel/lib/ansible/modules/identity/cyberark

#### Test Case
`pip install git+https://github.com/ansible-collection-migration/ansible-minimal`

**Comment by mkrizek** [comment]
With #178 merged, the error is now:
`error: can't copy 'lib/ansible/modules/system/_python_requirements_facts.py': doesn't exist or not a regular file`

**Comment by mkrizek** [comment]
> With #178 merged, the error is now:
> `error: can't copy 'lib/ansible/modules/system/_python_requirements_facts.py': doesn't exist or not a regular file`

I believe this is due to `lib/ansible/modules/system/_python_requirements_facts.py` missing in the spec file.
