### ISSUE TITLE
Handle removed/deprecated/aliases plugins

### ISSUE THREAD

**Issue by mkrizek** [ansible-community/collection_migration#187]
Currently, there are many removed and deprecated plugins (modules) (name starts with `_`) in https://github.com/ansible-collection-migration/ansible-minimal/. Aliases (name starts with `_` and the file is a symlink to other module) are currently removed from the checkout.

We need to decide how to handle them.

**Comment by pabelanger** [comment]
For network, when we last talked about migrating our collection we wanted to also move deprecated content, as to minimize the breaking changes to playbooks.  Having a flag to allow a collection to allow this would be helpful

**Comment by bcoca** [comment]
originally we were told that those would stay in core as collections would not support deprecation nor aliases, this has changed but we still don't know how that is going to look like, so until the feature is implemented we cannot migrate to it, keeping this open to handle the issue once we have something to migrate to.

**Comment by bcoca** [comment]
So I got some answers recently:

- deprecation will be recorded in `meta/deprecated.yml?` so we should remove leading _ when copying file and write an entry (hopefully will have example soon)

- 2 types of aliases, 'in same collection' can stay as symlinks, in diff collection required 'tombstone/redirect' which is also TBD.

**Comment by mattclay** [comment]
When migrating deprecated modules, make sure that the integration tests are migrated as well. While the modules have a `_` prefix, the integration test targets do not.

**Comment by bcoca** [comment]
closing via #395 and #407
