### ISSUE TITLE
duplicated unit tests code for collections

### ISSUE THREAD

**Issue by pabelanger** [ansible-community/collection_migration#191]
Greetings,

Today, for each new collection we need to migrated, do we also need to duplicate the following tests/unit code?  Is there a plan to refactor this into a shared library? Also, 

```console
$ tree 
.
├── compat
│   ├── builtins.py
│   ├── __init__.py
│   ├── mock.py
│   └── unittest.py
├── __init__.py
├── mock
│   ├── __init__.py
│   ├── loader.py
│   ├── path.py
│   ├── procenv.py
│   ├── vault_helper.py
│   └── yaml_helper.py
├── modules
│   ├── conftest.py
│   ├── __init__.py
│   └── utils.py
```

**Comment by pabelanger** [comment]
I suspect, this will be up to collection maintainers to solve, which isn't a bad thing. However, if this is a common pattern to all collections using ansible-test, we could move this into a shared library for all collections to want to use.

**Comment by gundalow** [comment]
* `compat/` hasn't changed for a year
* `mock/yaml_helper.py` changed a month ago, though rest  hasn't for years
* `modules/conftest.py` - 8 months
* `modules/utils` - 4 months

So these don't appear to change much, so the advantages to release them independently of Ansible Core seems low.

These files aren't needed to all Unit test, for example Grafana Collection only has a [single file](https://github.com/gundalow-collections/grafana/tree/master/tests/unit) `test_grafana_team.py ` under `test/units` and works correctly with ansible-minimal

**Comment by gundalow** [comment]
This made me think about the dependencies to run the ansible/ansible specific unit tests

so `ansible-test units --docker default test/units/cli/  test/units/template/ test/units/config/` etc needs at least:
```
test/units/compat/__init__.py
test/units/compat/mock.py
test/units/compat/unittest.py
test/units/mock/__init__.py
test/units/mock/loader.py
test/units/mock/path.py
test/units/mock/vault_helper.py
test/units/mock/yaml_helper.py
```

I hit some other issues, though I think most of the files that @pabelanger mentions are needed to test ansible/ansible and therefore may need to stay in ansible-minimal

**Comment by gundalow** [comment]
So from chatting with @abadger, we 
1) Should include these in ansible-minimal
2) May need @mattclay to update `ansible-test` so these get added to PYTHON_PATH 
3) Put the Unit test helpers in a different directory so that Collections can't import unit-tests

**Comment by mkrizek** [comment]
Somewhat related https://github.com/ansible-community/collection_migration/issues/100

**Comment by bcoca** [comment]
also see #131

**Comment by gundalow** [comment]
@bcoca https://github.com/ansible-community/collection_migration/issues/191#issuecomment-565047030

Should Ansible-minimal contain the dependencies for its own unit tests, I'm assuming yes, though this is most likely lower down the priority list. We need to update use-cases in `minimal/README.md`

**Comment by bcoca** [comment]
@gundalow at this point i'm not sure what current 'minimal' has become, I did not create it as a target but as a test tool for collections not to get false positives. I'm moving my efforts to a mintest scenario to avoid overlap.

**Comment by webknjaz** [comment]
@gundalow

> * `modules/conftest.py` - 8 months

This one is tricky. `conftest.py` is a *special* module that `pytest` automatically loads from test dirs. It usually contains reusable fixtures. If we want this to live in ansible/ansible, we'd have to expose it as a plugin via `pytest11` entrypoint using setuptools: https://docs.pytest.org/en/latest/writing_plugins.html#setuptools-entry-points.

**Comment by abadger** [comment]
pytest actually has several different ways to specify plugins:

https://docs.pytest.org/en/latest/writing_plugins.html#plugin-discovery-order-at-tool-startup

So ansible-test could make the test framework from conftest.py available to unittests in other ways than a setuptools plugin if that is easier.

**Comment by webknjaz** [comment]
I think the point here is to avoid injecting some `conftest.py` boilerplate so not sure if that makes more sense than just using entrypoints.

**Comment by webknjaz** [comment]
@abadger @pabelanger @gundalow This should allow us to drop `modules/conftest.py`: https://github.com/ansible/ansible/pull/66430.

**Comment by bcoca** [comment]
cc @mattclay from #328

**Comment by bcoca** [comment]
note: even if this code is dupe per collection, we might also need to keep it in core so probably have to create a 'remove blacklist'.

**Comment by webknjaz** [comment]
> a 'remove blacklist'.

We already have it: wrap any path with `UnmovablePathStr()` and that's it.

**Comment by gundalow** [comment]
Migration is done, closing all open PRs and issues.
