### ISSUE TITLE
ansible-minimal: Contains too many unit tests

### ISSUE THREAD

**Issue by gundalow** [ansible-community/collection_migration#193]
I did `find test/units/ -type f` and removed anything that obviously should be included, though there appears to be too many files still shipped.
```
test/units/modules/system/test_linux_mountinfo.py
test/units/modules/net_tools/test_hetzner_firewall.py
test/units/modules/net_tools/test_hetzner_firewall_info.py
test/units/modules/cloud/linode_v4/conftest.py
test/units/modules/cloud/linode_v4/test_linode_v4.py
test/units/modules/cloud/linode_v4/__init__.py
test/units/modules/cloud/google/test_gcp_url_map.py
test/units/modules/cloud/google/test_gcp_forwarding_rule.py
test/units/module_utils/hwc/test_dict_comparison.py
test/units/module_utils/hwc/test_hwc_utils.py
test/units/module_utils/net_tools/test_netbox.py
test/units/module_utils/test_distribution_version.py
test/units/module_utils/cloud/test_backoff.py
test/units/module_utils/postgresql/test_postgres.py
test/units/module_utils/identity/keycloak/test_keycloak_connect.py
test/units/module_utils/test_text.py
test/units/module_utils/aws/test_aws_module.py
test/units/module_utils/facts/test_collector.py
test/units/module_utils/facts/hardware/test_sunos_get_uptime_facts.py
test/units/module_utils/facts/hardware/linux_data.py
test/units/module_utils/facts/hardware/test_linux.py
test/units/module_utils/facts/hardware/test_linux_get_cpu_info.py
test/units/module_utils/facts/hardware/__init__.py
test/units/module_utils/facts/system/test_lsb.py
test/units/module_utils/facts/system/distribution/test_parse_distribution_file_ClearLinux.py
test/units/module_utils/facts/system/__init__.py
test/units/module_utils/facts/system/test_cmdline.py
test/units/module_utils/facts/other/test_ohai.py
test/units/module_utils/facts/other/test_facter.py
test/units/module_utils/facts/other/__init__.py
test/units/module_utils/facts/test_ansible_collector.py
test/units/module_utils/facts/test_timeout.py
test/units/module_utils/facts/test_collectors.py
test/units/module_utils/facts/fixtures/cpuinfo/armv6-rev7-1cpu-cpuinfo
test/units/module_utils/facts/fixtures/cpuinfo/aarch64-4cpu-cpuinfo
test/units/module_utils/facts/fixtures/cpuinfo/ppc64-power7-rhel7-8cpu-cpuinfo
test/units/module_utils/facts/fixtures/cpuinfo/x86_64-8cpu-cpuinfo
test/units/module_utils/facts/fixtures/cpuinfo/arm64-4cpu-cpuinfo
test/units/module_utils/facts/fixtures/cpuinfo/armv7-rev4-4cpu-cpuinfo
test/units/module_utils/facts/fixtures/cpuinfo/sparc-t5-debian-ldom-24vcpu
test/units/module_utils/facts/fixtures/cpuinfo/x86_64-4cpu-cpuinfo
test/units/module_utils/facts/fixtures/cpuinfo/x86_64-2cpu-cpuinfo
test/units/module_utils/facts/fixtures/cpuinfo/ppc64le-power8-24cpu-cpuinfo
test/units/module_utils/facts/fixtures/cpuinfo/armv7-rev3-8cpu-cpuinfo
test/units/module_utils/facts/fixtures/findmount_output.txt
test/units/module_utils/facts/network/test_fc_wwn.py
test/units/module_utils/facts/network/test_generic_bsd.py
test/units/module_utils/facts/network/__init__.py
test/units/module_utils/facts/network/test_iscsi_get_initiator.py
test/units/contrib/inventory/test_vmware_inventory.py
test/units/utils/amazon_placebo_fixtures.py
test/units/utils/kubevirt_fixtures.py
test/units/utils/test_encrypt.py
```

**Comment by mkrizek** [comment]
The above PR makes things a bit better, I updated the listing in the issue description to correspond with the state after #200 is merged.

**Comment by bcoca** [comment]
also see #131

**Comment by bcoca** [comment]
@gundalow many of those don't seem tied to specific modules and will probably require a manual pass to remove cruft, the 'facts' ones (the bulk of your list) should stay there if setup.py is in minmal

**Comment by gundalow** [comment]
@mkrizek thank you for your patch, that appears to have removed a lot of them.
@bcoca if you look at the edit history for my comment you'll see that #200 reduced the list a lot.

It's things like
```
test/units/modules/source_control/test_bitbucket_pipeline_variable.py
test/units/modules/source_control/test_bitbucket_access_key.py
test/units/modules/source_control/test_bitbucket_pipeline_key_pair.py
test/units/modules/source_control/test_bitbucket_pipeline_known_host.py
```
Which confuse me, none of the bitbucket modules are deprecated, or in https://github.com/ansible-collection-migration/ansible-minimal/tree/devel/lib/ansible/modules/source_control

Same for cloud/linode unit tests

**Comment by bcoca** [comment]
those are probably not matching the test detection, we still are working on that, in some cases we match 'too much' in others not enough, but most of the issues are with the former, but i would like to separate the cases and tackle them individually.

**Comment by mkrizek** [comment]
> 
> ```
> test/units/modules/source_control/test_bitbucket_pipeline_variable.py
> test/units/modules/source_control/test_bitbucket_access_key.py
> test/units/modules/source_control/test_bitbucket_pipeline_key_pair.py
> test/units/modules/source_control/test_bitbucket_pipeline_known_host.py
> ```

So these are not matched because we look at `test/units/modules/source_control/bitbucket` and not ` test/units/modules/source_control/` (missing `bitbucket` dir in the path) since those modules are in `lib/ansible/modules/source_control/bitbucket`.

**Comment by webknjaz** [comment]
@mkrizek so maybe we could `git mv` them in ansible/ansible?

**Comment by bcoca** [comment]
@webknjaz that might be better solution as expanding 'matching' for just these exceptions to the normal pattern might end up creating bigger issues.

**Comment by mkrizek** [comment]
Opened https://github.com/ansible/ansible/pull/66237 to move bitbucket tests in ansible/ansible.

**Comment by webknjaz** [comment]
@gundalow is this still an issue?

**Comment by bcoca** [comment]
I'm going to close this because:
- minimal is dead
- base has specific test issues open, this one is too generic
- unit/integration spec properties now allow specific test migration per collection
