### ISSUE TITLE
migrate.py doesn't rewrite connection to fqcn

### ISSUE THREAD

**Issue by pabelanger** [ansible-community/collection_migration#196]
In the case of ansible.netcommon, we have moved network_cli into this collection.  However, after running the migration script, connection: network_cli is not modified.

It should be

connection: ansible.netcommon.network_cli

**Comment by mkrizek** [comment]
Can you provide a simple reproducer in a form of a scenario file(s)?

**Comment by mkrizek** [comment]
Also the specific YAML file where the connection is not rewritten.
