### ISSUE TITLE
yaml multi-line block strings no longer formatted properly

### ISSUE THREAD

**Issue by pabelanger** [ansible-community/collection_migration#204]
We have some tests that use multi-line (literal) block strings, but after running migrate.py they are converted to single quotes string. This results in a breakage of testing.

**original**
```
- name: Remove Config
  cli_config:
    config: "{{ lines }}"
  vars:
    lines: |
      interface GigabitEthernet 0/1
      no ip address
      no ipv6 address
      interface GigabitEthernet 0/2
      no ip address
      no ipv6 address
```

**migrated**
```
- name: Remove Config
  vars:
    lines: 'interface GigabitEthernet 0/1

      no ip address

      no ipv6 address

      interface GigabitEthernet 0/2

      no ip address

      no ipv6 address

      '
  ansible.netcommon.cli_config:
    config: '{{ lines }}'
```

**Comment by sivel** [comment]
As far as I can tell, when these are parsed, they both match.  How is this breaking testing?

After running `yaml.safe_load` on both:

```
>>> one[0]['vars']['lines'] == two[0]['vars']['lines']
True
```

**Comment by bcoca** [comment]
@pabelanger if this is a yaml-lint issue, we are not going to address it since it is not part of our current testing.

**Comment by webknjaz** [comment]
I think it's because we use pyYAML. Martin and I have tried to bring in ruamel.yaml to avoid that much reformatting but atm Brian doesn't want us to rely on a YAML parser that differs from what ansible/ansible uses.
In general, such reformatting will probably mostly affect human readability keeping the machine-readable values unchanged.

**Comment by pabelanger** [comment]
Thanks for replies! I think the issue was result of working late, and manually modified yaml file _after_ migrate.py ran.  I'll close this for now, and testing a fresh run again. Sorry for the noise.
