### ISSUE TITLE
migrate ignore.txt 

### ISSUE THREAD

**Issue by bcoca** [ansible-community/collection_migration#219]
So generated collections can pass sanity tests (which now include validate-modules) we should copy relevant parts of ignore.txt to the collection (ignore-2.10.txt)

**Comment by webknjaz** [comment]
@bcoca I 100% implemented this earlier. Are you sure that it's not something else we're missing?

Look, both https://github.com/ansible-collection-migration/misc.glob/blob/master/tests/sanity/ignore-2.10.txt and https://github.com/ansible-collection-migration/misc.glob/blob/master/tests/sanity/ignore-2.9.txt include `validate-modules`. The script preserves everything as long as it exists in the target collection.

**Comment by webknjaz** [comment]
I don't know why but in my test org I saw green sanity tests under 2.7/2.6 and red with 3+. I suppose that ansible-test may behave differently with collections.

**Comment by webknjaz** [comment]
```console
ERROR: Found 13 action-plugin-docs issue(s) which need to be resolved:
ERROR: plugins/action/net_banner.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_interface.py:0:0: action plugin has no matching module to provide documentation
See documentation for help: https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/action-plugin-docs.html
ERROR: plugins/action/net_l2_interface.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_l3_interface.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_linkagg.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_lldp.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_lldp_interface.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_logging.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_static_route.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_system.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_user.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_vlan.py:0:0: action plugin has no matching module to provide documentation
ERROR: plugins/action/net_vrf.py:0:0: action plugin has no matching module to provide documentation
```

**Comment by bcoca** [comment]
@webknjaz you are correct, i assigned to you cause i thought we had discussed this already in the test/copy/rewrite implementation (clearly we did).

I just happened to randomly test with bigip .. which don't have an ignore and have non compliant modules that were merged and not updated since before the check went in (my luck makes for good QA).

so closing this as 'it works'tm since testing other modules sanity it does use the copied ignore*.txt files

**Comment by webknjaz** [comment]
> assigned to you

Actually you assigned to Martin and I noticed it as it looked like something that shouldn't actually be open :)
