### ISSUE TITLE
NWO: Consider whether to keep all of ini, toml, and yaml inventory plugins

### ISSUE THREAD

**Issue by abadger** [ansible-community/collection_migration#261]
Amongst the inventory plugins that we're keeping in base, we have three which are self-contained, file based lists of inventory hosts with vars: ini, toml, and yaml.  It doesn't feel like that fits our design goals where we're trying to limit future core maintenance and have a good justification for everything that stays.  (For instance, modules follow the line of be minimally useful on POSIX systems.  Callbacks follow the line of allow all command line switches to work.)

Here's pros and cons for each of the plugins:
**ini**
* Pros:
  * Status quo.  been ansible's go-to inventory plugin for the longest.
  * Likely the largest number of users
  * Most of our docs are assume this inventory format.  Same with third party blog posts and articles.
  * Simple for sysadmins to get started with
  * No external deps
* Cons:
  * Not as easy to code new features for.
  * schema is not well liked by the devs
  * Unable to parse using an existing standard as our ini format is too different.
  * Hard to programmatically generate this inventory (For instance, cannot dump to ini format in ansible-inventory and ansible-test is going to move away from its ini generated inventories to json serialized inventories in the future)

**yaml**
* Pros:
  * Been around longer than the toml inventory
  * Easier to do complex things with the yaml format than with the ini format
  * No new external deps as we already need pyyaml
  * ansible playbooks are also yaml so the schema is different but the format is the same (might be a red herring... just looks at the learning curve going from html to docbook to see how schema can be more important than format)
  * Can read inventories which third-party code has programmatically generated and written using the python stdlib json library
    * For ansible-test usage, this means the writing can be done even before any of our dependencies have been installed.
* Cons:
  * Schema is not well liked by the devs
  * Harder for a new sysadmin to learn than ini

**toml**
* Pros:
  * Close to ini so it is also simple to use
  * Better schema than the yaml plugin
  * Easier to do complex things than with the ini format
* Cons:
  * Requires an additional third-party library to read or write
    * Also see the yaml **Pros** for why ansible-test would really rather than we don't have a dep for writing.

Other notes:
* ansible-inventory can use yaml or toml to dump an inventory file that can be read by ansible.
  * ansible-inventory will fail gracefully if the toml library is not installed so it could be easily modified to fail gracefully if the toml plugin is not installed.
  * ansible-inventory does not use the yaml plugin for writing.
  * ansible-inventory defaults to json output.
  * ansible-inventory cannot dump in ini format so one of toml or yaml is needed in order for ansible-inventory to dump in a compatible format.

With all this information... it feels like:
* We must keep ini in ansible-base for 2.10.  it is the most popular inventory, documentation (ours and third party) assumes it is the inventory format, and it is simple to use.
* There are a lot of reasons to also support either the yaml or toml plugin (format is dumpable by ansible-inventory, allows more complex configuration than ini)
* Neither the yaml nor toml plugin are a clear winner over each other (yaml is harder to learn, has a bad schema; toml requires an additional dep) and neither seem to be a successor to ini.

My recommendation is to pick one of the yaml or toml plugins for inclusion in ansible-base 2.10 with the justification that it's better for complex inventories than ini.  If toml is chosen, add the toml library as a controller side dependency.  For a future version, lay out the requirements of a better complex inventory plugin and then roadmap creating a replacement that meets those criteria (it could be based on the present toml or yaml plugin or all new code).  Deprecate the chosen complex configuration in favor of the new one, with scripted conversion from the old format to the new one.

**Comment by sivel** [comment]
My vote is to keep them.  I believe the most important argument is that `ansible-inventory` can emit both `--yaml` and `--toml`.  `ansible-inventory` is not pluggable from the ability to emit formats.  If `ansible-inventory` can emit it, we should be able to consume it.

**Comment by thaumos** [comment]
My vote would be to keep them as well.  We need a bare minimum for people to start with. 

I would argue that most will start with ini over toml because I feel like that's what most people gravitate towards for first try. So if we are to keep just one, it would be ini.

**Comment by gundalow** [comment]
Migration is done, closing all open PRs and issues.
