### ISSUE TITLE
NWO: Remove excess cache plugins

### ISSUE THREAD

**Issue by abadger** [ansible-community/collection_migration#265]
We currently have the following cache plugins in base which implement caching to a file on the filesystem:

- jsonfile.py
- pickle.py
- yaml.py

None of these are the default (memory is).  It feels like we should either move all of them out of base as they aren't selectable via a dedicated commandline arg and it's definitely possible to use ansible without them or to keep at most one of them and justify it as "We have one supported plugin for caching which doesn't hold everything in memory".

**Comment by thaumos** [comment]
If they're not *needed* for running a controller, we can move them out.

**Comment by abadger** [comment]
Not having heard any further discussion on this, I'll open a PR to remove all three of those.
