### ISSUE TITLE
Use ansible from the checkout to evaluate test/filter plugins

### ISSUE THREAD

**Issue by mkrizek** [ansible-community/collection_migration#299]
We import tests and filters in migrate.py to see if they are moved to a collection. Since some of the tests/filters are being move around in ansible/ansible, we need to use the latest version to be accurate.

**Comment by webknjaz** [comment]
We shouldn't touch `requirements.txt`, it's autogenerated and is being automatically kept up-to-date by dependabot. Besides, it'll break because of `--require-hashes`. So installing devel should be a separate command executed after installing things from requirements.
