### ISSUE TITLE
Need to collect all third-party deps from tests

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/collection_migration#30]
https://github.com/ansible/collection_migration/runs/221518664#step:9:183:
```python-traceback
ImportError while loading conftest '/home/runner/work/collection_migration/collection_migration/.cache/collections/ansible_collections/ansible/amazon/tests/unit/module_utils/xenserver/conftest.py'.
/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/ansible/utils/collection_loader.py:228: in load_module
    exec(code_object, newmod.__dict__)
tests/unit/module_utils/xenserver/conftest.py:18: in <module>
    from mock import MagicMock
E   ModuleNotFoundError: No module named 'mock'
ERROR: Command "pytest ..." returned exit status 4.
```

--------------------------

Slack comment about installing test requirements by @mattclay:
> @webknjaz Testing with ``--docker``, ``--venv`` or ``--requirements`` will make sure all the requirements are installed. If you're using the latest devel version of ``ansible-test`` then you can have collections specific test requirements as well (for unit tests they go in ``tests/unit/requirements.txt``).

**Comment by mkrizek** [comment]
Closing per discussion on slack.
