### ISSUE TITLE
migrate.py should support marking integration test targets for migration

### ISSUE THREAD

**Issue by mattclay** [ansible-community/collection_migration#329]
Some integration test targets are not named after any module or plugin, yet still should be migrated along with the content they test. Below are some examples:

- vyos_smoke
- nxos_smoke
- nxos_become

Supporting specification of arbitrary integration test target names in scenario files would enable migration of these targets.

**Comment by mkrizek** [comment]
https://github.com/ansible-community/collection_migration/issues/131

**Comment by bcoca** [comment]
@mattclay are there more than those? since those are manually migrated and if there are no more, I would avoid adding complexity to the migrate.py script and just require removal when the manual migration is done.

**Comment by mattclay** [comment]
Yes, there are others. I haven't created an exhaustive list, but here are a few more I found easily:

- *_smoke - 6 targets (including 2 previously mentioned)
- mariadb_replication
- scaleway_s3
- synchronize-buildah

As well as the tests mentioned in https://github.com/ansible-community/collection_migration/issues/345

**Comment by gundalow** [comment]
May also need this to ensure that integration tests for inventory scripts are added.
