### ISSUE TITLE
migrate.py should support migration of the contrib directory

### ISSUE THREAD

**Issue by mattclay** [ansible-community/collection_migration#345]
The contrib directory contains scripts not essential for ansible-base, organized into two subdirectories:

- inventory - Inventory scripts that existed before inventory plugins.
- vault - Scripts to use with ansible-vault for sourcing passwords.

Some of the inventory scripts have integration tests executed in ansible/ansible CI:

- inventory_aws_conformance
- inventory_foreman_script
- vmware_inventory

The scripts in both of these directories need a new home outside of ansible-base. Migrating them into the relevant collections, despite them not being plugins, provides several benefits:

1. The scripts can live in the same repository as their related content. For example, the `vmware_inventory.py` script and test would likely belong with the other vmware modules. As with any other migrated content, if no other collection is appropriate, `community.general` would be used (unless a dedicated `community.scripts` or similar collection is desired).
2. Facilitates continued integration testing of the scripts which have them. Some of those tests depend on ansible-test, which requires a collection if it is not part of the ansible repo.
3. Removes content from the ansible repo which is not necessary for the functioning of ansible-base, and provides a clear new location for any such future content, if desired.

Migration would be simple, as files would only need to be moved to the appropriate collection.  Implementing https://github.com/ansible-community/collection_migration/issues/329 would provide a facility for migrating the associated tests.

Alternatively all of the content could be moved manually, but doing that manually after each migration for further testing seems unnecessary if the migration can be done automatically.

**Comment by webknjaz** [comment]
I don't think there's any designated place for non-plugin scripts in the collection structure spec: https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html / https://docs.ansible.com/ansible/devel/user_guide/collections_using.html / https://docs.ansible.com/ansible/devel/dev_guide/collections_galaxy_meta.html

I'm not sure where'd we put them. What do you have in mind?

Also, since these scripts would live in collections, it's fair to expect that there'd be a way of referring them via FQDN and making the "script" inventory plugin know how to invoke things like "ns.coll.contrib.inventory.foreman", for example. Any thoughts?

**Comment by mattclay** [comment]
Although there is no designated place in collections for non-plugin content, they can contain any type of file in any directory. I suggest `scripts/inventory` and `scripts/vault`, but any structure could be used.

The intent here is to store the scripts in the collection, not make them accessible as collection content. No new features are needed to integrate them as plugins or make them accessible using a FQDN. They're simply arbitrary files that would continue to be used exactly as they are today, just developed alongside related content and outside of ansible-base.

**Comment by bcoca** [comment]
inventory scripts are already supported with `inventory_scripts` key.
The only scenario in which they were used was to not to migrate to specific collections, just all of them to their own, and later abandoned. 

As for vault, there has not been a request to do so, easy to implement, but really 4 files that are 2 methods and easily done manually.

**Comment by mattclay** [comment]
@bcoca Thanks, I wasn't aware of `inventory_scripts` support. I'll open a PR using that. Hopefully that will be enough to close this issue. I'll provide an update here once PR(s) are opened.

**Comment by mattclay** [comment]
@gundalow is going to open PRs to migrate the inventory scripts to the appropriate collections.

**Comment by gundalow** [comment]
Community inventory scripts: https://github.com/ansible-community/collection_migration/pull/363

**Comment by bcoca** [comment]
closing as per above
