### ISSUE TITLE
[NWO] Need collections created for posix and windows

### ISSUE THREAD

**Issue by thaumos** [ansible-community/collection_migration#352]
We need to keep clear separation for what plugins are maintained by the Ansible Core team separate of what will exist in ansible-base or the community collection. 

For example:
Windows collection
Posix collection (name is not considered to be final, just to help deliver a point). 

Also, these can be compiled of many collections and do not or are meant to be a final representation as decided to be best mapped by our team.

**Comment by jctanner** [comment]
'''
filename,fqn,namespace,name,current_support_level,new_support_level,botmeta_migrated_to,scenario_file,scenario_plugin_type,matched_line
lib/ansible/module_utils/compat/ipaddress.py,ansible.netcommon,ansible,netcommon,core,community,,scenarios/nwo/ansible.yml,module_utils,compat/ipaddress.py
lib/ansible/module_utils/ec2.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,module_utils,ec2.py
lib/ansible/module_utils/ismount.py,community.general,community,general,core,community,,unclaimed!,module_utils,unclaimed!
lib/ansible/module_utils/net_tools/nios/api.py,community.general,community,general,core,community,,unclaimed!,module_utils,unclaimed!
lib/ansible/modules/cloud/amazon/_ec2_vpc_net_facts.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/_ec2_vpc_net_facts.py
lib/ansible/modules/cloud/amazon/_ec2_vpc_subnet_facts.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/_ec2_vpc_subnet_facts.py
lib/ansible/modules/cloud/amazon/aws_s3.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/aws_s3.py
lib/ansible/modules/cloud/amazon/cloudformation.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/cloudformation.py
lib/ansible/modules/cloud/amazon/ec2.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/ec2.py
lib/ansible/modules/cloud/amazon/ec2_group.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/ec2_group.py
lib/ansible/modules/cloud/amazon/ec2_metadata_facts.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/ec2_metadata_facts.py
lib/ansible/modules/cloud/amazon/ec2_snapshot.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/ec2_snapshot.py
lib/ansible/modules/cloud/amazon/ec2_vol.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/ec2_vol.py
lib/ansible/modules/cloud/amazon/ec2_vpc_net.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/ec2_vpc_net.py
lib/ansible/modules/cloud/amazon/ec2_vpc_net_info.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/ec2_vpc_net_info.py
lib/ansible/modules/cloud/amazon/ec2_vpc_subnet.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/ec2_vpc_subnet.py
lib/ansible/modules/cloud/amazon/ec2_vpc_subnet_info.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/ec2_vpc_subnet_info.py
lib/ansible/modules/cloud/amazon/s3_bucket.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,modules,cloud/amazon/s3_bucket.py
lib/ansible/modules/files/acl.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/files/assemble.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/files/synchronize.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/system/at.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/system/authorized_key.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/system/mount.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/system/seboolean.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/system/selinux.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/system/sysctl.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/async_status.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/setup.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/slurp.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_acl.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_acl.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_acl_inheritance.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_acl_inheritance.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_command.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_command.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_copy.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_copy.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_disk_image.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_disk_image.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_dns_client.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_dns_client.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_domain.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_domain.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_domain_controller.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_domain_controller.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_domain_membership.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_domain_membership.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_file.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_file.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_get_url.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_get_url.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_group.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_group.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_owner.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_owner.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_package.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_package.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_path.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_path.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_ping.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_ping.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_reboot.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_regedit.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_regedit.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_service.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_service.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_share.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_share.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_shell.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_shell.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_stat.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_stat.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_template.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_updates.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_updates.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_user.ps1,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/modules/windows/win_user.py,community.general,community,general,core,community,,unclaimed!,modules,unclaimed!
lib/ansible/plugins/action/assemble.py,community.general,community,general,core,community,,unclaimed!,action,unclaimed!
lib/ansible/plugins/action/aws_s3.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,action,aws_s3.py
lib/ansible/plugins/action/patch.py,community.general,community,general,core,community,,unclaimed!,action,unclaimed!
lib/ansible/plugins/action/synchronize.py,community.general,community,general,core,community,,unclaimed!,action,unclaimed!
lib/ansible/plugins/action/telnet.py,community.general,community,general,core,community,,unclaimed!,action,unclaimed!
lib/ansible/plugins/action/win_copy.py,community.general,community,general,core,community,,unclaimed!,action,unclaimed!
lib/ansible/plugins/action/win_reboot.py,community.general,community,general,core,community,,unclaimed!,action,unclaimed!
lib/ansible/plugins/action/win_template.py,community.general,community,general,core,community,,unclaimed!,action,unclaimed!
lib/ansible/plugins/action/win_updates.py,community.general,community,general,core,community,,unclaimed!,action,unclaimed!
lib/ansible/plugins/callback/debug.py,community.general,community,general,core,community,,unclaimed!,callback,unclaimed!
lib/ansible/plugins/callback/profile_roles.py,community.general,community,general,core,community,,unclaimed!,callback,unclaimed!
lib/ansible/plugins/callback/profile_tasks.py,community.general,community,general,core,community,,unclaimed!,callback,unclaimed!
lib/ansible/plugins/connection/aws_ssm.py,community.amazon,community,amazon,core,community,,scenarios/nwo/community.yml,connection,aws_ssm.py
lib/ansible/plugins/connection/chroot.py,community.general,community,general,core,community,,unclaimed!,connection,unclaimed!
lib/ansible/plugins/connection/funcd.py,community.general,community,general,core,community,,unclaimed!,connection,unclaimed!
lib/ansible/plugins/connection/iocage.py,community.general,community,general,core,community,,unclaimed!,connection,unclaimed!
lib/ansible/plugins/connection/jail.py,community.general,community,general,core,community,,unclaimed!,connection,unclaimed!
lib/ansible/plugins/connection/libvirt_lxc.py,community.general,community,general,core,community,,unclaimed!,connection,unclaimed!
lib/ansible/plugins/connection/lxc.py,community.general,community,general,core,community,,unclaimed!,connection,unclaimed!
lib/ansible/plugins/connection/lxd.py,community.general,community,general,core,community,,unclaimed!,connection,unclaimed!
lib/ansible/plugins/connection/napalm.py,ansible.netcommon,ansible,netcommon,core,community,,scenarios/nwo/ansible.yml,connection,napalm.py
lib/ansible/plugins/connection/persistent.py,ansible.netcommon,ansible,netcommon,core,community,,scenarios/nwo/ansible.yml,connection,persistent.py
lib/ansible/plugins/connection/qubes.py,community.general,community,general,core,community,,unclaimed!,connection,unclaimed!
lib/ansible/plugins/connection/zone.py,community.general,community,general,core,community,,unclaimed!,connection,unclaimed!
lib/ansible/plugins/loader.py,community.general,community,general,core,community,,unclaimed!,plugins,unclaimed!
lib/ansible/plugins/lookup/nios.py,community.general,community,general,core,community,,unclaimed!,lookup,unclaimed!
lib/ansible/plugins/lookup/nios_next_ip.py,community.general,community,general,core,community,,unclaimed!,lookup,unclaimed!
lib/ansible/plugins/lookup/nios_next_network.py,community.general,community,general,core,community,,unclaimed!,lookup,unclaimed!
lib/ansible/plugins/shell/csh.py,community.general,community,general,core,community,,unclaimed!,shell,unclaimed!
lib/ansible/plugins/shell/fish.py,community.general,community,general,core,community,,unclaimed!,shell,unclaimed!
lib/ansible/plugins/strategy/debug.py,community.general,community,general,core,community,,unclaimed!,strategy,unclaimed!
lib/ansible/plugins/strategy/host_pinned.py,community.general,community,general,core,community,,unclaimed!,strategy,unclaimed!
'''

**Comment by jctanner** [comment]
https://github.com/ansible-community/collection_migration/pull/362

**Comment by jborean93** [comment]
For the Windows collections the split should be easy to see (https://github.com/ansible-community/collection_migration/pull/377)

* `ansible.windows` - Contains core plugins supported by us
* `community.windows` - Community plugins not supported by us

The `ansible.windows` collection will be published as is to Automation Hub and Galaxy while `community.windows` will be published as is to just Galaxy.

**Comment by gundalow** [comment]
Was done

Migration is done, closing all open PRs and issues.
