### ISSUE TITLE
[NWO] community.general issues

### ISSUE THREAD

**Issue by gundalow** [ansible-community/collection_migration#357]
Dumping ground for the issues I've found so far.

Feel free to keep on editing this issue to update if there are issues filed that cover these problems

1. `plugins/action/fortios_config.py` exists, though module isn't FIX: https://github.com/ansible-community/collection_migration/pull/358
2. `plugins/callback/actionable.py` has `extends_documentation_fragment: default_callback`, though that isn't included in community.general
3. `./tests/sanity/ignore-2.X.txt` doesn't include lines for plugins starting with `_`, ie `plugins/modules/_ovirt_affinity_label_facts.py`. 
4. `tests/unit/module_utils/xenserver/conftest.py` and `tests/unit/modules/cloud/xenserver/conftest.py` have `from ..FakeAnsibleModule import FakeAnsibleModule` where as should be single `.`
5. `tests/unit/modules/remote_management/oneview/hpe_test_utils.py`  should `self.testing_module = getattr(ansible.modules.remote_management.oneview, testing_module)` python import be updated?

### Others
a. need to decide where other Azure content should live

**Comment by webknjaz** [comment]
> * `./tests/sanity/ignore-2.X.txt` doesn't include lines for plugins starting with `_`, ie `plugins/modules/_ovirt_affinity_label_facts.py`.

Have you checked that core includes it? We currently just take the original file and delete all the lines that point to files that don't exist in a given collection...

**Comment by webknjaz** [comment]
> 5\. `tests/unit/modules/remote_management/oneview/hpe_test_utils.py`  should `self.testing_module = getattr(ansible.modules.remote_management.oneview, testing_module)` python import be updated?

Is oneview included in the scenario?

**Comment by gundalow** [comment]
> > 5. `tests/unit/modules/remote_management/oneview/hpe_test_utils.py`  should `self.testing_module = getattr(ansible.modules.remote_management.oneview, testing_module)` python import be updated?
> 
> Is oneview included in the scenario?

@webknjaz `oneview` is in community.general according to the csv file

**Comment by webknjaz** [comment]
@gundalow then it's a bug, file a separate issue.

**Comment by bcoca** [comment]
> plugins/callback/actionable.py has extends_documentation_fragment: default_callback, though that isn't included in community.general

not an issue, that is in core and should stay there, a good indication is that the fragment does not use FQCN which would be required if fragment existed in collection.

**Comment by gundalow** [comment]
> > plugins/callback/actionable.py has extends_documentation_fragment: default_callback, though that isn't included in community.general
> 
> not an issue, that is in core and should stay there, a good indication is that the fragment does not use FQCN which would be required if fragment existed in collection.

the produced community.general has this problem, so something is broken

**Comment by bcoca** [comment]
@gundalow true, but it is not because of the fragment being in core, which it must be since the default callback is there, it is because the indentation is off.

**Comment by gundalow** [comment]
Migration is done, closing all open PRs and issues.
