### ISSUE TITLE
migrate.py doesn't copy all ignore.txt lines

### ISSUE THREAD

**Issue by gundalow** [ansible-community/collection_migration#364]
ignore.txt can contain entries for non-plugins, it appears that these are not always copied into the new collection

devel
```
grep sendProcessStdin.py test/sanity/ignore.txt 
test/integration/targets/supervisorctl/files/sendProcessStdin.py future-import-boilerplate
test/integration/targets/supervisorctl/files/sendProcessStdin.py metaclass-boilerplate
```

community.general
```
grep sendProcessStdin.py tests/sanity/ignore-2.*
```

**Comment by bcoca** [comment]
it only copies matches it can find, which does not include aliases at this point

**Comment by gundalow** [comment]
This causes CI failures, so added blocker label

**Comment by webknjaz** [comment]
So it looks like it's added to `sanity.txt` if specified explicitly:
```yaml
integration:
- supervisorctl/files/sendProcessStdin.py
```

This hints me to check how auto-discovered files get into the list... Hopefully, I'll find a reproducer.
