### ISSUE TITLE
module parameter handled as a module name

### ISSUE THREAD

**Issue by goneri** [ansible-community/collection_migration#370]
Hi!

I've a case where a functional test with a 'mail' module attribute is wrongly rename 'community.general.mail'.

https://github.com/ansible/ansible/blob/devel/test/integration/targets/vmware_vcenter_settings/tasks/main.yml#L29

I was using version a785aebf294d5cad066de2934d16448f70e37bfe during the run.

**Comment by mkrizek** [comment]
Note to self: per bcoca's suggestion this https://github.com/ansible/ansible/blob/f49f14e8c7d0e219cb8b8b2730678a8bbabefd84/lib/ansible/parsing/mod_args.py#L262 could be used to indicate whether it's a task or not.
