### ISSUE TITLE
migrate.py must separate test and runtime collection dependencies

### ISSUE THREAD

**Issue by mattclay** [ansible-community/collection_migration#379]
Currently all collection dependencies are stored under `dependencies` in `galaxy.yml`. The collections generated by `migrate.py` include both test and runtime dependencies in this list, which turns all test dependencies into runtime dependencies.

This results in AH collections having runtime dependencies on Galaxy collections. AH collections should only have test, not runtime, dependencies on Galaxy collections.

`migrate.py` should be updated to write test dependencies to a separate requirements file such as `tests/requirements.yml` and omit them from `galaxy.yml`.  That will at least allow us to see and work with the discovered test and runtime dependencies separately.

@nitzmahone and I are still working on figuring out what the final specification for test dependencies will look like, but we shouldn't wait for that to update `migrate.py` to split them.

**Comment by bcoca** [comment]
galaxy.yml was just a placeholder till we got a 'defined location' for test requirements. Now that we have it, it should be a simple patch.
