### ISSUE TITLE
migrate.py misses migration of integration tests for deprecated modules

### ISSUE THREAD

**Issue by mattclay** [ansible-community/collection_migration#381]
When `migrate.py` migrates deprecated modules such as `_vmware_dvs_portgroup_facts` it does not migrate the associated integration tests `vmware_dvs_portgroup_facts`, most likely because the leading `_` is not removed before looking for tests.

**Comment by mkrizek** [comment]
https://github.com/ansible-collection-migration/ansible-base/tree/devel/test/integration/targets/vmware_dvs_portgroup_facts (404) -> https://github.com/ansible-collection-migration/community.vmware/tree/master/tests/integration/targets/vmware_dvs_portgroup_facts
