### ISSUE TITLE
seealso modules are not migrated

### ISSUE THREAD

**Issue by jborean93** [ansible-community/collection_migration#399]
If a module has a `seealso` section in it's documentation it is not migrated across https://github.com/ansible-collection-migration/ansible.windows/blob/d8ebbeb662f8112f3c0998ebe221f5f38c5bb2e0/plugins/modules/win_regedit.py#L95-L97.

The first module is in the same collection but probably should be the FQCN while the latter is in another collection. I'm unsure whether we should still keep the link with the new FQCN or just remove it.

**Comment by webknjaz** [comment]
Do you mean that the modules that are listed under `seealso` should be migrated to the same collection?

**Comment by jborean93** [comment]
No I mean either the entry should have the module name rewritten as a FQCN to the eventual target or just stripped out if it's not in the same collection. I don't know how the doc build will work for stuff migrated outside of Ansible but here is what it currently looks like in latest https://github.com/ansible-community/collection_migration/issues/400

![image](https://user-images.githubusercontent.com/8462645/74769388-0d6dcc80-52d6-11ea-9c0b-35fc1f687164.png)

**Comment by webknjaz** [comment]
I think there's some tools that work with collection-local identifiers that are not in a form of FQCN, like tests. Can't the docs builder prepend the FQCN where needed, while rendering?

**Comment by bcoca** [comment]
@webknjaz not just doc builder, ansible-doc also would need this to be FQCN
