### ISSUE TITLE
Migrated tests newlines are removed

### ISSUE THREAD

**Issue by jborean93** [ansible-community/collection_migration#400]
The migrated tests have newlines removed from the output making the tests harder to understand.

Before: https://github.com/ansible/ansible/blob/093e2460b27476541baa3457ac7c9c887117c285/test/integration/targets/setup_win_device/tasks/main.yml

After: https://github.com/ansible-collection-migration/ansible.windows/blob/master/tests/integration/targets/setup_win_device/tasks/main.yml

**Comment by mkrizek** [comment]
FWIW https://github.com/ansible-community/collection_migration/pull/405 will skip rewriting if there are no changes and therefore will preserve the formatting.

**Comment by bcoca** [comment]
not much we can do, limted by yaml dumper options. avoiding uneeded rewrites as above is the best we can do within current time constraints.
