### ISSUE TITLE
Migrated tests have long lines or multiline strings reformatted

### ISSUE THREAD

**Issue by jborean93** [ansible-community/collection_migration#401]
A migrated test has lines that exceed ~100 chars reformatted to split it across new lines. An example is

Before: https://github.com/ansible/ansible/blob/093e2460b27476541baa3457ac7c9c887117c285/test/integration/targets/setup_win_device/tasks/main.yml

```
- name: get name of the dummy network adapter
  win_shell: (Get-CimInstance -Class Win32_NetworkAdapter -Filter "Name='{{ network_device_name }}'").NetConnectionID
  changed_when: False
  register: network_adapter_name_raw
```

After: https://github.com/ansible-collection-migration/ansible.windows/blob/master/tests/integration/targets/setup_win_device/tasks/main.yml

```
- name: get name of the dummy network adapter
  win_shell: (Get-CimInstance -Class Win32_NetworkAdapter -Filter "Name='{{ network_device_name
    }}'").NetConnectionID
  changed_when: false
```

Normally this isn't a massive issue but it does cause some problems with some inline scripts in Ansible but multi line strings become unreadable like the [win_acl tests](https://github.com/ansible-collection-migration/ansible.windows/blob/d8ebbeb662f8112f3c0998ebe221f5f38c5bb2e0/tests/integration/targets/win_acl/tasks/tests.yml#L3).

Before it [looks like](https://github.com/ansible/ansible/blob/bb70c0b996f762a0aeccd08050f45882cf6ddbc6/test/integration/targets/win_acl/tasks/tests.yml#L3-L24) but after it [looks like](https://github.com/ansible-collection-migration/ansible.windows/blob/d8ebbeb662f8112f3c0998ebe221f5f38c5bb2e0/tests/integration/targets/win_acl/tasks/tests.yml#L1-L12).

**Comment by webknjaz** [comment]
It's because of PyYAML. Until somebody allows us to render with ruamel.yaml, there's probably nothing we can do.

**Comment by jborean93** [comment]
Which part is (or both)? The newline separator or multi line string conversion

**Comment by webknjaz** [comment]
Likely both. We don't do anything other than calling yaml.dumps and putting that into files.

**Comment by mkrizek** [comment]
FWIW #405 will skip rewriting if there are no changes and therefore will preserve the formatting.
