### ISSUE TITLE
Rewritten modules should respect 160 chars line length limit

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/collection_migration#41]
When running sanity tests against migrated collections, I've hit line length errors on lines like
```python
from ansible_collections.new_azure_order.azure.plugins.module_utils.azure_rm_common import AzureRMModuleBase, azure_id_to_dict, normalize_location_name, format_resource_id
```

Instead, we should emit
```python
from ansible_collections.new_azure_order.azure.plugins.module_utils.azure_rm_common \
    import (
        AzureRMModuleBase,
        azure_id_to_dict,
        normalize_location_name,
        format_resource_id,
    )
```
or
```python
from ansible_collections.new_azure_order.azure.plugins.module_utils.azure_rm_common import AzureRMModuleBase
from ansible_collections.new_azure_order.azure.plugins.module_utils.azure_rm_common import azure_id_to_dict
from ansible_collections.new_azure_order.azure.plugins.module_utils.azure_rm_common import normalize_location_name
from ansible_collections.new_azure_order.azure.plugins.module_utils.azure_rm_common import format_resource_id 
```

**Comment by webknjaz** [comment]
This is pointed out by the sanity tests after the migration. We should have sanity tests green.

**Comment by bcoca** [comment]
ansible sanity tests should be green, again, collections might differ, but once we have rest of migration right i'll revisit. closing this issue, but keeping PR open.

**Comment by webknjaz** [comment]
Reopening because I closed the PR. I think the implementation needs to invoke isort instead. As a bonus, we could inject an isort config into migrated collections.

**Comment by mkrizek** [comment]
> Reopening because I closed the PR. I think the implementation needs to invoke isort instead. As a bonus, we could inject an isort config into migrated collections.

For the record, it seems that there is no way to tell `isort` to skip reordering imports so I am not sure it's the right tool for us to use to wrap import lines to be less than 160 chars. So it's either sanity tests failing on lines being longer than 160 chars or imports being placed incorrectly - because `isort` puts all imports at the top of the file but sanity checks require imports to be after `DOCUMENTATION`.

**Comment by webknjaz** [comment]
Seems like it's supported with a comment: https://github.com/timothycrosley/isort/issues/393#issuecomment-570898631

Or like this: https://github.com/timothycrosley/isort/issues/468#issuecomment-570899233

If somebody were to implement it, they'd have to inject smth like 
```python
from __future__ import ...

# isort: off
DOCUMENTATION = """
...
"""
# isort: on

from ansible import other.things
```

or:
```python
from __future__ import ...

DOCUMENTATION = """
...
"""
# isort: split

from ansible import other.things
```

**Comment by gundalow** [comment]
Migration is done, closing all open PRs and issues.
