### ISSUE TITLE
migrate.py leaves behind orphaned test targets

### ISSUE THREAD

**Issue by mattclay** [ansible-community/collection_migration#410]
Many integration test targets have dependencies on test targets which are only used as dependencies. Once migration is complete, unused dependency targets remain in ansible-base, since all targets depending on them have been migrated.

It would be helpful to remove these orphaned targets as part of the migration, making it easier to see what will remain after migration. Alternatively these targets could be manually removed after migration.

Targets eligible for removal are those that are only used as dependencies. These targets meet at least one of the following criteria:

- contain the `hidden` alias
- name starts with `setup_` or `prepare_`

I don't know what dependency detection logic `migrate.py` currently has, but `ansible-test` detects dependencies using the following mechanisms:

- use of `meta` dependencies
- use of `needs/target/{target_name}` aliases
- use of `setup/once/{target_name}` aliases
- use of `setup/always/{target_name}` aliases
- symbolic links to files in another target

NOTE: Dependencies can be recursive.

**Comment by mkrizek** [comment]
We already process:
* use of `meta` dependencies
* use of `needs/target/{target_name}` aliases

I am working on adding support for `symbolic links to files in another target` as a part of #411.

**Comment by mkrizek** [comment]
These are added in https://github.com/ansible-community/collection_migration/pull/435:
* use of `setup/once/{target_name}` aliases
* use of `setup/always/{target_name}` aliases
