### ISSUE TITLE
migrate.py should preserve test symlinks

### ISSUE THREAD

**Issue by mattclay** [ansible-community/collection_migration#411]
Symbolic links are used in integration tests to share files within and across test targets. They are also used to indicate dependencies between test targets.

Migration should preserve symbolic links in test targets. All symbolic links will either be within the same target or to another target which is in the same collection, so converting the symbolic links to files is unnecessary.

**Comment by bcoca** [comment]
This was probably due to the --convert-symlinks option what was part of CI until recently, it did a blanket conversion of symlinks to original files.
