### ISSUE TITLE
Generate BOTMETA for community.general, AWS, VMware,Windows

### ISSUE THREAD

**Issue by gundalow** [ansible-community/collection_migration#429]
For the big collections where we will be running Ansibulbot we will need a `.github/BOTMETA.yml` file generating.

* Based on ansible/ansible:devel's botmeta, though stripped down to only the relevant files
* Honor teams
* file paths updated

**Comment by gundalow** [comment]
Should be part of option specification

**Comment by jctanner** [comment]
With 2 weeks left of migrate.py development before we run it for the very last time, and how trivial it is for someone to create a BOTMETA.yml file by hand or automatically, this is definitely not a blocker. We have other things that are more important to fix.

**Comment by gundalow** [comment]
Resolved by https://github.com/ansible/ansibullbot/pull/1293
