### ISSUE TITLE
migrate.py leaves behind directories with only empty __init__.py

### ISSUE THREAD

**Issue by mattclay** [ansible-community/collection_migration#442]
Previously `migrate.py` would remove directories which contained only other directories and empty `__init__.py` files. Now these directories remain after migration.

Here is one example:

https://github.com/ansible-collection-migration/ansible-base/blob/devel/lib/ansible/module_utils/network/ios/providers/cli/config/bgp/__init__.py

**Comment by bcoca** [comment]
currently we only clean out module dirs, but i can add module_utils, just did not since we did have 'non empty __init__.py there'
