### ISSUE TITLE
migrate.py not creating migrated_to: entries in BOTMETA.yml for all content which has been migrated

### ISSUE THREAD

**Issue by abadger** [ansible-community/collection_migration#456]
https://github.com/ansible-collection-migration/ansible-base/blob/devel/.github/BOTMETA.yml#L419 Only has the following entry for modules/cloud/hcloud:

```
  $modules/cloud/hcloud/: &hcloud
    keywords: [ hcloud, hetzner cloud ]
    labels: [ cloud, hcloud ]
    maintainers: $team_hcloud
```

There's no `migrate_to:` entry there.  But if you look in the cloud directory: https://github.com/ansible-collection-migration/ansible-base/tree/devel/lib/ansible/modules/cloud

The end state should look like one of the following:
```
  $modules/cloud/hcloud/: &hcloud
    keywords: [ hcloud, hetzner cloud ]
    labels: [ cloud, hcloud ]
    maintainers: $team_hcloud
  $modules/cloud/hcloud/hcloud_datacenter_info.py
    migrated_to: community.general
  $modules/cloud/hcloud/hcloud_floating_ip.py
    migrated_to: community.general
[...]
  $modules/cloud/hcloud/hcloud_volume_info.py
    migrated_to: community.general
```

or
```
  $modules/cloud/hcloud/hcloud_datacenter_info.py
    keywords: [ hcloud, hetzner cloud ]
    labels: [ cloud, hcloud ]
    maintainers: $team_hcloud
    migrated_to: community.general
  $modules/cloud/hcloud/hcloud_floating_ip.py
    keywords: [ hcloud, hetzner cloud ]
    labels: [ cloud, hcloud ]
    maintainers: $team_hcloud
    migrated_to: community.general
[...]
  $modules/cloud/hcloud/hcloud_volume_info.py
    keywords: [ hcloud, hetzner cloud ]
    labels: [ cloud, hcloud ]
    maintainers: $team_hcloud
    migrated_to: community.general
```

I'm not sure how ansibullbot intends for overlapping BOTMETA entries to be normalized and merged.

**Comment by webknjaz** [comment]
If you look closer at https://github.com/ansible-collection-migration/ansible-base/tree/devel/.github, you'll see that `BOTMETA.yml` was last modified in a commit from core, not the one that migration script created. I'd guess that the bug in `migrate.py` that it doesn't commit this file for some reason.

**Comment by webknjaz** [comment]
Oh: https://github.com/ansible-community/collection_migration/blame/bfb7f9925db36feff9e9e5261d21f034574cbc51/migrate.py#L1888-L1889

**Comment by bcoca** [comment]
as discussed offline this was temporarily disabled for testing diff scenarios, it was reenabled in recent commit so closing this issue.
