### ISSUE TITLE
migrate.py incorrectly removes unit test __init__.py file

### ISSUE THREAD

**Issue by mattclay** [ansible-community/collection_migration#490]
The migration script is removing some unit test `__init__.py` files in directories that are not empty.

For example, this file exists in devel:

https://github.com/ansible/ansible/blob/devel/test/units/plugins/connection/__init__.py

But it is missing after migration:

https://github.com/ansible-collection-migration/ansible-base/tree/devel/test/units/plugins/connection

This breaks imports on unit tests.

**Comment by mkrizek** [comment]
Fixed in https://github.com/ansible-community/collection_migration/commit/f348a47e16c8ab39b557816341a5388bda099530
