### ISSUE TITLE
Rewrite implicit relative Python 2 imports to be explicit

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/collection_migration#80]
Basically, we need to mutate code like this:
```diff
-from oneview_module_loader import SOME_CONSTANT  # doesn't work
+from .oneview_module_loader import SOME_CONSTANT  # works
```
if the imported module is next to the current one.

pytest does some injections into PYTHONPATH which don't work with the collection loader in place so we have to do the rewrite.

**Comment by bcoca** [comment]
not going to consider this a blocker, if we cannot reliably detect the rewrite, we can punt to the 'collection maintainers' to fix as a 'known issue you need to look for'.

**Comment by gundalow** [comment]
> not going to consider this a blocker, if we cannot reliably detect the rewrite, we can punt to the 'collection maintainers' to fix as a 'known issue you need to look for'.

How are we tracking these known issues? Leaving the issue open, adding a "knownissue" label?

**Comment by bcoca** [comment]
@gundalow im writting 2 docs, one for 'if you are manually migrating, these are the steps WE took and you maybe want to do same' and another for 'future maintainers' of what migrate.py produces with 'this is what we did and theses are possible lingering issues to watch out for' . 

Currently there are several issues with documentation we are probably not going to be able to solve, this one seems a likely candidate to join them.

**Comment by webknjaz** [comment]
> if we cannot reliably detect the rewrite

I think it's easy to detect: just check if there's a file/dir/path with this name in the same folder as the current module.
